name: news_pbp
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  adaptive_theme: ^3.4.0
  sqflite: ^2.2.6
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  image_picker: ^0.8.4+4
  path_provider: ^2.0.5
  flutter_slidable: ^0.6.0
  flutter_tts: ^3.6.2
  speech_to_text: ^6.4.0
  camera: ^0.10.5+2 # access to hardware
  mobile_scanner: ^3.2.0 # scan qr code
  qr_flutter: ^4.1.0
  url_launcher: ^6.2.1
  qr_code_scanner: ^1.0.1
  pdf: ^3.6.4
  printing: ^5.9.0
  intl: ^0.17.0
  responsive_sizer: ^3.2.0
  uuid: ^3.0.6
  http: ^1.1.0
  flutter_riverpod: ^2.4.8
  flutter_rating_bar: ^4.0.1
  sqflite_common_ffi: ^2.3.0+4
  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  popover: ^0.2.8+2
  toastification: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter
  msix: ^3.16.7

msix_config:
  display_name: ditonton
  publisher_display_name: asdos company
  identity_name: com.example.news-pbp
  logo_path: D:\Dendy\KULIAH\PANITIA\logo atma jaya.png
  msix_version: 1.0.0.0
  capabilities: internetClient

flutter:
  uses-material-design: true
  assets:
    - images/
